import type { Listing, TransportJob } from '@/lib/data'
import type { Submission } from '../types'
import {
  compact,
  isoString,
  nullable,
  type Row,
  type TableSpec,
} from './sql-repository'

export const listingTable: TableSpec<Listing> = {
  table: 'listings',
  columns: [
    'id',
    'name',
    'category',
    'maker',
    'year',
    'hours',
    'condition',
    'prefecture',
    'city',
    'image',
    'summary',
    'deals',
    'sale_price',
    'rent_per_day',
    'rent_to_own',
    'seller_name',
    'seller_kind',
    'seller_rating',
    'seller_reviews',
    'tags',
    'created_at',
    'updated_at',
  ],
  toRow: (listing) => [
    listing.id,
    listing.name,
    listing.category,
    listing.maker,
    listing.year,
    listing.hours,
    listing.condition,
    listing.prefecture,
    listing.city,
    listing.image,
    listing.summary,
    listing.deals,
    nullable(listing.salePrice),
    nullable(listing.rentPerDay),
    nullable(listing.rentToOwn),
    listing.seller.name,
    listing.seller.kind,
    listing.seller.rating,
    listing.seller.reviews,
    listing.tags,
    nullable(listing.createdAt),
    nullable(listing.updatedAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      name: row.name as string,
      category: row.category as string,
      maker: row.maker as string,
      year: row.year as number,
      hours: row.hours as number,
      condition: row.condition as Listing['condition'],
      prefecture: row.prefecture as string,
      city: row.city as string,
      image: row.image as string,
      summary: row.summary as string,
      deals: row.deals as Listing['deals'],
      salePrice: (row.sale_price as number | null) ?? undefined,
      rentPerDay: (row.rent_per_day as number | null) ?? undefined,
      rentToOwn: (row.rent_to_own as boolean | null) ?? undefined,
      seller: {
        name: row.seller_name as string,
        kind: row.seller_kind as Listing['seller']['kind'],
        rating: row.seller_rating as number,
        reviews: row.seller_reviews as number,
      },
      tags: row.tags as string[],
      createdAt: isoString(row.created_at),
      updatedAt: isoString(row.updated_at),
    }),
}

export const transportJobTable: TableSpec<TransportJob> = {
  table: 'transport_jobs',
  columns: [
    'id',
    'item',
    'from_location',
    'to_location',
    'distance_km',
    'weight',
    'desired_date',
    'reward',
    'status',
    'created_at',
    'updated_at',
  ],
  toRow: (job) => [
    job.id,
    job.item,
    job.from,
    job.to,
    job.distanceKm,
    job.weight,
    job.desiredDate,
    job.reward,
    job.status,
    nullable(job.createdAt),
    nullable(job.updatedAt),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      item: row.item as string,
      from: row.from_location as string,
      to: row.to_location as string,
      distanceKm: row.distance_km as number,
      weight: row.weight as string,
      desiredDate: row.desired_date as string,
      reward: row.reward as number,
      status: row.status as TransportJob['status'],
      createdAt: isoString(row.created_at),
      updatedAt: isoString(row.updated_at),
    }),
}

export const submissionTable: TableSpec<Submission> = {
  table: 'submissions',
  columns: ['id', 'kind', 'target_id', 'received_at', 'payload'],
  toRow: (submission) => [
    submission.id,
    submission.kind,
    nullable(submission.targetId),
    submission.receivedAt,
    JSON.stringify(submission.payload),
  ],
  fromRow: (row: Row) =>
    compact({
      id: row.id as string,
      kind: row.kind as Submission['kind'],
      targetId: (row.target_id as string | null) ?? undefined,
      receivedAt: isoString(row.received_at) as string,
      payload: row.payload as Record<string, unknown>,
    }),
}
