import 'server-only'

import { orderStatusLabels, type Listing, type TransportJob } from '@/lib/data'
import { countRentalDays, rentalStatusLabels } from '@/lib/rent-to-own'
import type {
  AccountStatus,
  CarrierProfile,
  DealEvent,
  DealKind,
  Message,
  Notification,
  Order,
  Rental,
  Review,
  Submission,
  ThreadRead,
} from './store/types'

/**
 * What the marketplace looks like after a few months of use: purchases,
 * rentals, threads, hauls, and reviews between the demo accounts and the
 * personas. Loaded on top of the sample listings unless `DEMO_ACTIVITY=off`.
 */
export type DemoActivity = {
  listings: Listing[]
  transportJobs: TransportJob[]
  submissions: Submission[]
  messages: Message[]
  rentals: Rental[]
  orders: Order[]
  reviews: Review[]
  carrierProfiles: CarrierProfile[]
  notifications: Notification[]
  threadReads: ThreadRead[]
  accountStatuses: AccountStatus[]
  dealEvents: DealEvent[]
}

/** `at('09-13 10:30')` → ISO timestamp in 2026, JST. */
function at(stamp: string): string {
  const [date, time] = stamp.split(' ')
  return new Date(`2026-${date}T${time}:00+09:00`).toISOString()
}

const tractorImage = '/equipment/tractor.png'

const listings: Listing[] = [
  {
    id: 'trc-101',
    name: 'クボタ トラクター 33馬力 スラッガー',
    category: 'トラクター',
    maker: 'クボタ',
    year: 2021,
    hours: 310,
    condition: '目立った傷なし',
    prefecture: '新潟県',
    city: '長岡市',
    image: tractorImage,
    summary:
      '中型の33馬力。畦塗り機と合わせて使っていました。まずはレンタルでどうぞ。',
    deals: ['sale', 'rent'],
    salePrice: 9_800_000,
    rentPerDay: 15_000,
    rentToOwn: true,
    rentToOwnCreditRate: 50,
    rentToOwnCreditCap: 2_500_000,
    seller: { name: '出品者デモ', kind: '農業法人', rating: 4.8, reviews: 34 },
    tags: ['中型', '4WD'],
    ownerUserId: 'demo-seller',
    createdAt: at('09-13 09:10'),
    updatedAt: at('09-13 09:10'),
    moderationStatus: 'pending',
  },
  {
    id: 'cmb-102',
    name: '三菱 コンバイン 3条刈 VY',
    category: 'コンバイン',
    maker: '三菱',
    year: 2015,
    hours: 520,
    condition: '使用感あり',
    prefecture: '山形県',
    city: '鶴岡市',
    image: '/equipment/combine.png',
    summary: '今年の稲刈りを最後に手放します。刈り取り後の引き渡し希望。',
    deals: ['sale'],
    salePrice: 6_200_000,
    rentToOwn: false,
    seller: { name: '山田農産', kind: '農業法人', rating: 4.7, reviews: 63 },
    tags: ['3条刈', '整備記録あり'],
    ownerUserId: 'yamada-nosan',
    createdAt: at('09-12 18:40'),
    updatedAt: at('09-12 18:40'),
    moderationStatus: 'pending',
  },
  {
    id: 'til-103',
    name: 'クボタ 管理機 陽菜 TRS70',
    category: '耕運機',
    maker: 'クボタ',
    year: 2020,
    hours: 45,
    condition: '未使用に近い',
    prefecture: '東京都',
    city: '八王子市',
    image: '/equipment/tiller.png',
    summary: '運営が検証用に出品している小型管理機。週末レンタル向け。',
    deals: ['rent'],
    rentPerDay: 3_000,
    rentToOwn: false,
    seller: { name: '運営デモ', kind: '法人', rating: 0, reviews: 0 },
    tags: ['小型', '初心者向け'],
    ownerUserId: 'demo-admin',
    createdAt: at('08-30 11:00'),
    updatedAt: at('08-30 11:20'),
    moderationStatus: 'approved',
    moderatedAt: at('08-30 11:20'),
  },
  {
    id: 'til-104',
    name: 'ホンダ 管理機 F220 サラダ',
    category: '耕運機',
    maker: 'ホンダ',
    year: 2021,
    hours: 30,
    condition: '未使用に近い',
    prefecture: '新潟県',
    city: '長岡市',
    image: '/equipment/tiller.png',
    summary: '家庭菜園用に購入したもの。ほぼ新品です。',
    deals: ['sale'],
    salePrice: 98_000,
    rentToOwn: false,
    seller: { name: '出品者デモ', kind: '農業法人', rating: 4.8, reviews: 34 },
    tags: ['小型', '軽トラ積載可'],
    ownerUserId: 'demo-seller',
    createdAt: at('07-20 09:00'),
    updatedAt: at('08-12 16:00'),
    moderationStatus: 'approved',
    moderatedAt: at('07-20 10:00'),
    withdrawnAt: at('08-12 16:00'),
  },
  {
    id: 'rpl-105',
    name: 'クボタ 田植機 4条植 ラクエル',
    category: '田植機',
    maker: 'クボタ',
    year: 2018,
    hours: 150,
    condition: '目立った傷なし',
    prefecture: '新潟県',
    city: '南魚沼市',
    image: '/equipment/rice-planter.png',
    summary: '規模拡大で6条に買い替えたため売却。',
    deals: ['sale'],
    salePrice: 1_450_000,
    rentToOwn: false,
    seller: {
      name: '中村ファーム',
      kind: '農業法人',
      rating: 4.8,
      reviews: 34,
    },
    tags: ['4条植', '低稼働'],
    ownerUserId: 'nakamura-farm',
    createdAt: at('06-05 08:30'),
    updatedAt: at('07-02 12:00'),
    moderationStatus: 'approved',
    moderatedAt: at('06-05 09:00'),
    withdrawnAt: at('07-02 12:00'),
  },
  {
    id: 'drn-106',
    name: '農業用ドローン 16Lタンク 散布用',
    category: 'ドローン',
    maker: 'DJI系',
    year: 2024,
    hours: 40,
    condition: '未使用に近い',
    prefecture: '新潟県',
    city: '長岡市',
    image: '/equipment/drone.png',
    summary: '防除シーズン向けに貸し出し中。オペレーター資格をお持ちの方に。',
    deals: ['rent'],
    rentPerDay: 14_000,
    rentToOwn: false,
    seller: { name: '出品者デモ', kind: '農業法人', rating: 4.8, reviews: 34 },
    tags: ['防除', '短期OK'],
    ownerUserId: 'demo-seller',
    createdAt: at('08-01 10:00'),
    updatedAt: at('08-01 10:30'),
    moderationStatus: 'approved',
    moderatedAt: at('08-01 10:30'),
  },
]

const transportJobs: TransportJob[] = [
  {
    id: 'tj-101',
    item: 'トラクター 45馬力（キャビン付）',
    from: '新潟県 長岡市',
    to: '新潟県 新潟市',
    distanceKm: 60,
    weight: '約1.8t',
    desiredDate: '9/13 午前',
    reward: 18_000,
    status: '運搬中',
    ownerUserId: 'demo-seller',
    createdAt: at('09-08 09:00'),
    updatedAt: at('09-13 08:05'),
    moderationStatus: 'approved',
    moderatedAt: at('09-08 09:30'),
  },
  {
    id: 'tj-102',
    item: '田植機 6条植',
    from: '富山県 砺波市',
    to: '長野県 飯山市',
    distanceKm: 130,
    weight: '約0.9t',
    desiredDate: '9/20 終日',
    reward: 32_000,
    status: '調整中',
    ownerUserId: 'ito-farm',
    createdAt: at('09-05 14:00'),
    updatedAt: at('09-11 17:30'),
    moderationStatus: 'approved',
    moderatedAt: at('09-05 14:20'),
  },
  {
    id: 'tj-103',
    item: '管理機 2台（軽トラ積載可）',
    from: '群馬県 前橋市',
    to: '埼玉県 深谷市',
    distanceKm: 45,
    weight: '約250kg',
    desiredDate: '相談',
    reward: 7_000,
    status: '募集中',
    ownerUserId: 'kato',
    createdAt: at('09-13 07:45'),
    updatedAt: at('09-13 07:45'),
    moderationStatus: 'pending',
  },
  {
    id: 'tj-104',
    item: '田植機 4条植',
    from: '新潟県 南魚沼市',
    to: '群馬県 高崎市',
    distanceKm: 140,
    weight: '約0.6t',
    desiredDate: '7/5 午前',
    reward: 28_000,
    status: '完了',
    ownerUserId: 'nakamura-farm',
    createdAt: at('06-28 10:00'),
    updatedAt: at('07-05 15:40'),
    moderationStatus: 'approved',
    moderatedAt: at('06-28 10:30'),
  },
]

function rental(
  input: Omit<Rental, 'days' | 'rentTotal' | 'createdAt' | 'updatedAt'> & {
    createdAt: string
    updatedAt: string
  },
): Rental {
  const days = countRentalDays(input.startDate, input.endDate)
  return { ...input, days, rentTotal: days * input.rentPerDay }
}

const rentals: Rental[] = [
  rental({
    id: 'r-101',
    listingId: 'trc-001',
    renterUserId: 'demo-user',
    startDate: '2026-10-05',
    endDate: '2026-10-08',
    rentPerDay: 22_000,
    salePrice: 18_800_000,
    creditRate: 50,
    creditCap: 5_000_000,
    status: 'requested',
    createdAt: at('09-12 20:15'),
    updatedAt: at('09-12 20:15'),
  }),
  rental({
    id: 'r-102',
    listingId: 'drn-005',
    renterUserId: 'suzuki',
    startDate: '2026-09-10',
    endDate: '2026-09-16',
    rentPerDay: 12_000,
    status: 'active',
    createdAt: at('09-01 09:30'),
    updatedAt: at('09-10 08:00'),
  }),
  rental({
    id: 'r-103',
    listingId: 'rpl-003',
    renterUserId: 'demo-user',
    startDate: '2026-08-20',
    endDate: '2026-08-24',
    rentPerDay: 18_000,
    salePrice: 9_600_000,
    creditRate: 50,
    creditCap: 2_500_000,
    status: 'completed',
    createdAt: at('08-10 12:00'),
    updatedAt: at('08-25 09:10'),
  }),
  rental({
    id: 'r-104',
    listingId: 'cmb-002',
    renterUserId: 'demo-admin',
    startDate: '2026-10-01',
    endDate: '2026-10-03',
    rentPerDay: 45_000,
    salePrice: 24_500_000,
    creditRate: 50,
    creditCap: 6_000_000,
    status: 'requested',
    createdAt: at('09-13 08:50'),
    updatedAt: at('09-13 08:50'),
  }),
  rental({
    id: 'r-105',
    listingId: 'trc-001',
    renterUserId: 'ito-farm',
    startDate: '2026-07-01',
    endDate: '2026-07-05',
    rentPerDay: 22_000,
    salePrice: 18_800_000,
    creditRate: 50,
    creditCap: 5_000_000,
    status: 'completed',
    createdAt: at('06-20 15:00'),
    updatedAt: at('07-06 10:00'),
  }),
  rental({
    id: 'r-106',
    listingId: 'til-004',
    renterUserId: 'takahashi',
    startDate: '2026-09-01',
    endDate: '2026-09-02',
    rentPerDay: 2_500,
    status: 'cancelled',
    createdAt: at('08-28 19:00'),
    updatedAt: at('08-30 08:20'),
  }),
  rental({
    id: 'r-107',
    listingId: 'drn-106',
    renterUserId: 'demo-user',
    startDate: '2026-09-12',
    endDate: '2026-09-18',
    rentPerDay: 14_000,
    status: 'active',
    createdAt: at('09-03 10:00'),
    updatedAt: at('09-12 07:30'),
  }),
  rental({
    id: 'r-108',
    listingId: 'cmb-002',
    renterUserId: 'suzuki',
    startDate: '2026-06-10',
    endDate: '2026-06-12',
    rentPerDay: 45_000,
    salePrice: 24_500_000,
    creditRate: 50,
    creditCap: 6_000_000,
    status: 'completed',
    createdAt: at('05-30 13:00'),
    updatedAt: at('06-13 11:00'),
  }),
]

const orders: Order[] = [
  {
    id: 'o-101',
    listingId: 'cmb-002',
    buyerUserId: 'suzuki',
    sellerUserId: 'demo-seller',
    price: 24_500_000,
    status: 'requested',
    message: '6月にレンタルした際の状態が良かったので購入したいです。',
    createdAt: at('09-13 09:40'),
    updatedAt: at('09-13 09:40'),
  },
  {
    id: 'o-102',
    listingId: 'trc-006',
    buyerUserId: 'demo-user',
    sellerUserId: 'tokachi-agri',
    price: 21_000_000,
    status: 'requested',
    message: '輸送は運搬マッチングで手配する予定です。',
    createdAt: at('09-11 21:00'),
    updatedAt: at('09-11 21:00'),
  },
  {
    id: 'o-103',
    listingId: 'til-004',
    buyerUserId: 'ito-farm',
    sellerUserId: 'kobayashi-engei',
    price: 128_000,
    status: 'accepted',
    createdAt: at('09-09 10:00'),
    updatedAt: at('09-10 09:15'),
  },
  {
    id: 'o-104',
    listingId: 'til-104',
    buyerUserId: 'demo-user',
    sellerUserId: 'demo-seller',
    price: 98_000,
    status: 'completed',
    createdAt: at('08-05 12:00'),
    updatedAt: at('08-12 16:00'),
  },
  {
    id: 'o-105',
    listingId: 'rpl-105',
    buyerUserId: 'kato',
    sellerUserId: 'nakamura-farm',
    price: 1_450_000,
    status: 'completed',
    createdAt: at('06-20 09:00'),
    updatedAt: at('07-02 12:00'),
  },
  {
    id: 'o-106',
    listingId: 'trc-006',
    buyerUserId: 'demo-admin',
    sellerUserId: 'tokachi-agri',
    price: 21_000_000,
    status: 'cancelled',
    message: '検証用の申込です。',
    createdAt: at('09-02 15:00'),
    updatedAt: at('09-03 09:00'),
  },
]

const submissions: Submission[] = [
  {
    id: 's-101',
    kind: 'listingInquiry',
    targetId: 'trc-001',
    userId: 'suzuki',
    receivedAt: at('09-13 10:05'),
    payload: {
      mode: 'rent',
      name: '鈴木さん',
      email: 'suzuki@example.com',
      preferredDate: '2026-10-20',
      message: '10月下旬に1週間ほど借りたいです。ロータリーは付属しますか？',
    },
  },
  {
    id: 's-102',
    kind: 'listingInquiry',
    targetId: 'cmb-002',
    userId: 'demo-user',
    receivedAt: at('09-11 19:20'),
    payload: {
      mode: 'question',
      name: '利用者デモ',
      email: 'user@example.com',
      message: '乾燥機との組み合わせは相談できますか？',
    },
    status: 'in_progress',
  },
  {
    id: 's-103',
    kind: 'listingInquiry',
    targetId: 'til-004',
    userId: 'kato',
    receivedAt: at('09-06 08:00'),
    payload: {
      mode: 'buy',
      name: '加藤さん',
      email: 'kato@example.com',
      message: '購入希望です。引き取りに伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-104',
    kind: 'listingInquiry',
    targetId: 'drn-005',
    userId: 'demo-admin',
    receivedAt: at('09-12 11:30'),
    payload: {
      mode: 'rent',
      name: '運営デモ',
      email: 'admin@example.com',
      preferredDate: '2026-09-25',
      message: '講習用に2日間借りられますか？',
    },
  },
  {
    id: 's-105',
    kind: 'transportApplication',
    targetId: 'tj-101',
    userId: 'okada',
    receivedAt: at('09-08 12:00'),
    payload: {
      name: '岡田さん',
      email: 'okada@example.com',
      vehicle: '2tトラック',
      availableDate: '2026-09-13',
      message: '当日午前に伺えます。',
    },
    status: 'agreed',
  },
  {
    id: 's-106',
    kind: 'transportApplication',
    targetId: 'tj-01',
    userId: 'hokuriku-unso',
    receivedAt: at('09-13 09:55'),
    payload: {
      name: '北陸運送',
      email: 'hokuriku-unso@example.com',
      vehicle: '4tトラック',
      availableDate: '2026-09-28',
      message: '大仙から天童は定期便のルートです。',
    },
  },
  {
    id: 's-107',
    kind: 'transportApplication',
    targetId: 'tj-05',
    userId: 'demo-user',
    receivedAt: at('09-12 16:45'),
    payload: {
      name: '利用者デモ',
      email: 'user@example.com',
      vehicle: '2tトラック',
      availableDate: '2026-10-12',
    },
  },
  {
    id: 's-108',
    kind: 'transportInquiry',
    targetId: 'tj-02',
    userId: 'yamamoto-transport',
    receivedAt: at('09-10 13:10'),
    payload: { message: '積み込みにフォークリフトは用意されますか？' },
    status: 'in_progress',
  },
  {
    id: 's-109',
    kind: 'transportApplication',
    targetId: 'tj-102',
    userId: 'hokuriku-unso',
    receivedAt: at('09-06 09:00'),
    payload: {
      name: '北陸運送',
      email: 'hokuriku-unso@example.com',
      vehicle: '4tトラック',
      availableDate: '2026-09-20',
    },
    status: 'agreed',
  },
  {
    id: 's-110',
    kind: 'transportApplication',
    targetId: 'tj-104',
    userId: 'yamamoto-transport',
    receivedAt: at('06-29 10:00'),
    payload: {
      name: '山本トランスポート',
      email: 'yamamoto-transport@example.com',
      vehicle: 'トレーラー',
      availableDate: '2026-07-05',
    },
    status: 'agreed',
  },
  {
    id: 's-111',
    kind: 'listingInquiry',
    targetId: 'trc-006',
    userId: 'takahashi',
    receivedAt: at('08-20 20:00'),
    payload: {
      mode: 'buy',
      name: '高橋さん',
      email: 'takahashi@example.com',
      message: '値下げの相談はできますか？',
    },
    status: 'declined',
  },
  {
    id: 's-112',
    kind: 'transportInquiry',
    targetId: 'tj-01',
    userId: 'demo-user',
    receivedAt: at('09-12 09:00'),
    payload: { message: '希望日の前日搬入でも大丈夫ですか？' },
    status: 'in_progress',
  },
]

const messages: Message[] = [
  {
    id: 'm-101',
    threadId: 's-102',
    senderUserId: 'demo-seller',
    body: '乾燥機は別途ご相談ください。搬入も合わせて見積もりします。',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'm-102',
    threadId: 's-112',
    senderUserId: 'demo-seller',
    body: '前日搬入で問題ありません。倉庫の鍵は当日お渡しします。',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'm-103',
    threadId: 's-103',
    senderUserId: 'kobayashi-engei',
    body: 'ありがとうございます。9月中の引き取りでお願いします。',
    createdAt: at('09-06 18:00'),
  },
  {
    id: 'm-104',
    threadId: 's-108',
    senderUserId: 'demo-seller',
    body: 'フォークリフトは出発地に用意があります。',
    createdAt: at('09-10 15:00'),
  },
]

const reviews: Review[] = [
  {
    id: 'rv-101',
    listingId: 'til-104',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'demo-user',
    sourceKind: 'order',
    sourceId: 'o-104',
    rating: 5,
    comment: '説明どおりほぼ新品でした。引き渡しもスムーズ。',
    createdAt: at('08-13 21:00'),
  },
  {
    id: 'rv-102',
    listingId: 'rpl-003',
    sellerUserId: 'tamura',
    reviewerUserId: 'demo-user',
    sourceKind: 'rental',
    sourceId: 'r-103',
    rating: 5,
    comment: '整備が行き届いていて、初めての6条でも扱いやすかったです。',
    createdAt: at('08-26 07:40'),
  },
  {
    id: 'rv-103',
    listingId: 'trc-001',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'ito-farm',
    sourceKind: 'rental',
    sourceId: 'r-105',
    rating: 4,
    comment: '状態は良好。返却時の清掃基準を事前に聞いておくと安心です。',
    createdAt: at('07-07 09:00'),
  },
  {
    id: 'rv-104',
    listingId: 'rpl-105',
    sellerUserId: 'nakamura-farm',
    reviewerUserId: 'kato',
    sourceKind: 'order',
    sourceId: 'o-105',
    rating: 4,
    comment: '価格相応。運搬の手配まで相談に乗ってもらえました。',
    createdAt: at('07-04 19:30'),
  },
  {
    id: 'rv-105',
    listingId: 'cmb-002',
    sellerUserId: 'demo-seller',
    reviewerUserId: 'suzuki',
    sourceKind: 'rental',
    sourceId: 'r-108',
    rating: 3,
    comment: '機体は問題なし。受け渡し時間の連絡がやや遅めでした。',
    createdAt: at('06-14 20:10'),
  },
]

const carrierProfiles: CarrierProfile[] = [
  {
    id: 'demo-user',
    name: '利用者デモ',
    kind: '個人',
    prefecture: '新潟県',
    vehicles: ['2tトラック'],
    serviceAreas: ['新潟県', '長野県', '富山県'],
    note: '週末中心に対応できます。',
    createdAt: at('08-15 10:00'),
    updatedAt: at('08-15 10:00'),
  },
  {
    id: 'okada',
    name: '岡田さん',
    kind: '個人',
    prefecture: '新潟県',
    vehicles: ['軽トラック', '2tトラック'],
    serviceAreas: ['新潟県'],
    createdAt: at('07-10 09:00'),
    updatedAt: at('07-10 09:00'),
  },
  {
    id: 'hokuriku-unso',
    name: '北陸運送',
    kind: '法人',
    prefecture: '石川県',
    vehicles: ['4tトラック', 'トレーラー'],
    serviceAreas: ['石川県', '富山県', '福井県', '新潟県', '秋田県', '山形県'],
    note: '北陸〜東北の定期便あり。',
    createdAt: at('05-12 11:00'),
    updatedAt: at('08-01 11:00'),
  },
  {
    id: 'yamamoto-transport',
    name: '山本トランスポート',
    kind: '法人',
    prefecture: '北海道',
    vehicles: ['4tトラック', 'トレーラー'],
    serviceAreas: ['北海道', '新潟県', '群馬県'],
    createdAt: at('04-20 09:00'),
    updatedAt: at('04-20 09:00'),
  },
]

const notifications: Notification[] = [
  {
    id: 'n-101',
    userId: 'demo-seller',
    kind: 'inquiry',
    title: '問い合わせが届きました',
    body: 'クボタ トラクター 45馬力 GLシリーズ',
    href: '/account/threads/s-101',
    createdAt: at('09-13 10:05'),
  },
  {
    id: 'n-102',
    userId: 'demo-seller',
    kind: 'application',
    title: '応募が届きました',
    body: 'コンバイン 4条刈',
    href: '/account/threads/s-106',
    createdAt: at('09-13 09:55'),
  },
  {
    id: 'n-103',
    userId: 'demo-seller',
    kind: 'rental',
    title: '購入の申込が届きました',
    body: 'ヤンマー コンバイン 4条刈 AGシリーズ',
    href: '/account',
    createdAt: at('09-13 09:40'),
  },
  {
    id: 'n-104',
    userId: 'demo-seller',
    kind: 'rental',
    title: 'レンタルの申込が届きました',
    body: 'ヤンマー コンバイン 4条刈 AGシリーズ',
    href: '/account',
    createdAt: at('09-13 08:50'),
  },
  {
    id: 'n-105',
    userId: 'demo-seller',
    kind: 'application',
    title: '運搬が始まりました',
    body: 'トラクター 45馬力（キャビン付）',
    href: '/transport/tj-101',
    createdAt: at('09-13 08:05'),
  },
  {
    id: 'n-106',
    userId: 'demo-seller',
    kind: 'rental',
    title: 'レンタルの申込が届きました',
    body: 'クボタ トラクター 45馬力 GLシリーズ',
    href: '/account',
    createdAt: at('09-12 20:15'),
    readAt: at('09-12 21:00'),
  },
  {
    id: 'n-107',
    userId: 'demo-seller',
    kind: 'application',
    title: '案件への質問が届きました',
    body: 'トラクター 45馬力',
    href: '/account/threads/s-108',
    createdAt: at('09-10 13:10'),
    readAt: at('09-10 14:55'),
  },
  {
    id: 'n-108',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'ヤンマー コンバイン 4条刈 AGシリーズ',
    href: '/account/threads/s-102',
    createdAt: at('09-12 08:30'),
  },
  {
    id: 'n-109',
    userId: 'demo-user',
    kind: 'reply',
    title: '返信が届きました',
    body: 'コンバイン 4条刈',
    href: '/account/threads/s-112',
    createdAt: at('09-12 12:10'),
  },
  {
    id: 'n-110',
    userId: 'demo-user',
    kind: 'rental',
    title: `レンタルが「${rentalStatusLabels.active}」になりました`,
    body: '農業用ドローン 16Lタンク 散布用',
    href: '/account',
    createdAt: at('09-12 07:30'),
  },
  {
    id: 'n-111',
    userId: 'demo-user',
    kind: 'rental',
    title: `レンタルが「${rentalStatusLabels.completed}」になりました`,
    body: 'イセキ 田植機 6条植 さなえ',
    href: '/account',
    createdAt: at('08-25 09:10'),
    readAt: at('08-25 12:00'),
  },
  {
    id: 'n-112',
    userId: 'demo-user',
    kind: 'rental',
    title: `購入が「${orderStatusLabels.completed}」になりました`,
    body: 'ホンダ 管理機 F220 サラダ',
    href: '/account',
    createdAt: at('08-12 16:00'),
    readAt: at('08-12 18:30'),
  },
  {
    id: 'n-113',
    userId: 'demo-admin',
    kind: 'moderation',
    title: '出品が承認されました',
    body: 'クボタ 管理機 陽菜 TRS70',
    href: '/listings/til-103',
    createdAt: at('08-30 11:20'),
    readAt: at('08-30 11:25'),
  },
  {
    id: 'n-114',
    userId: 'demo-admin',
    kind: 'rental',
    title: `購入が「${orderStatusLabels.cancelled}」になりました`,
    body: 'ジョンディア トラクター 90馬力 大規模向け',
    href: '/account',
    createdAt: at('09-03 09:00'),
  },
]

const threadReads: ThreadRead[] = [
  { threadId: 's-102', userId: 'demo-seller', readAt: at('09-12 08:30') },
  { threadId: 's-112', userId: 'demo-seller', readAt: at('09-12 12:10') },
  { threadId: 's-108', userId: 'demo-seller', readAt: at('09-10 15:00') },
  { threadId: 's-105', userId: 'demo-seller', readAt: at('09-09 18:00') },
  { threadId: 's-103', userId: 'kobayashi-engei', readAt: at('09-06 18:00') },
].map((read) => ({ id: `${read.threadId}:${read.userId}`, ...read }))

const accountStatuses: AccountStatus[] = [
  {
    id: 'watanabe',
    status: 'suspended',
    note: '本人確認の書類が未提出',
    updatedAt: at('09-04 10:00'),
  },
]

type EventSeed = [DealKind, string, string, string | undefined, string, string?]

/** [kind, dealId, status, actor, when, note] — order does not matter. */
const eventSeeds: EventSeed[] = [
  [
    'order',
    'o-101',
    'requested',
    'suzuki',
    '09-13 09:40',
    '6月にレンタルした際の状態が良かったので購入したいです。',
  ],
  [
    'order',
    'o-102',
    'requested',
    'demo-user',
    '09-11 21:00',
    '輸送は運搬マッチングで手配する予定です。',
  ],
  ['order', 'o-103', 'requested', 'ito-farm', '09-09 10:00'],
  ['order', 'o-103', 'accepted', 'kobayashi-engei', '09-10 09:15'],
  ['order', 'o-104', 'requested', 'demo-user', '08-05 12:00'],
  ['order', 'o-104', 'accepted', 'demo-seller', '08-06 08:00'],
  ['order', 'o-104', 'delivered', 'demo-seller', '08-10 14:00'],
  ['order', 'o-104', 'completed', 'demo-user', '08-12 16:00'],
  ['order', 'o-105', 'requested', 'kato', '06-20 09:00'],
  ['order', 'o-105', 'accepted', 'nakamura-farm', '06-21 07:30'],
  ['order', 'o-105', 'delivered', 'nakamura-farm', '06-30 11:00'],
  ['order', 'o-105', 'completed', 'kato', '07-02 12:00'],
  [
    'order',
    'o-106',
    'requested',
    'demo-admin',
    '09-02 15:00',
    '検証用の申込です。',
  ],
  ['order', 'o-106', 'cancelled', 'demo-admin', '09-03 09:00'],
  [
    'rental',
    'r-101',
    'requested',
    'demo-user',
    '09-12 20:15',
    '2026-10-05 〜 2026-10-08',
  ],
  [
    'rental',
    'r-102',
    'requested',
    'suzuki',
    '09-01 09:30',
    '2026-09-10 〜 2026-09-16',
  ],
  ['rental', 'r-102', 'active', 'sky-agri', '09-10 08:00'],
  [
    'rental',
    'r-103',
    'requested',
    'demo-user',
    '08-10 12:00',
    '2026-08-20 〜 2026-08-24',
  ],
  ['rental', 'r-103', 'active', 'tamura', '08-20 09:00'],
  ['rental', 'r-103', 'completed', 'tamura', '08-25 09:10'],
  [
    'rental',
    'r-104',
    'requested',
    'demo-admin',
    '09-13 08:50',
    '2026-10-01 〜 2026-10-03',
  ],
  [
    'rental',
    'r-105',
    'requested',
    'ito-farm',
    '06-20 15:00',
    '2026-07-01 〜 2026-07-05',
  ],
  ['rental', 'r-105', 'active', 'demo-seller', '07-01 08:30'],
  ['rental', 'r-105', 'completed', 'demo-seller', '07-06 10:00'],
  [
    'rental',
    'r-106',
    'requested',
    'takahashi',
    '08-28 19:00',
    '2026-09-01 〜 2026-09-02',
  ],
  ['rental', 'r-106', 'cancelled', 'takahashi', '08-30 08:20'],
  [
    'rental',
    'r-107',
    'requested',
    'demo-user',
    '09-03 10:00',
    '2026-09-12 〜 2026-09-18',
  ],
  ['rental', 'r-107', 'active', 'demo-seller', '09-12 07:30'],
  [
    'rental',
    'r-108',
    'requested',
    'suzuki',
    '05-30 13:00',
    '2026-06-10 〜 2026-06-12',
  ],
  ['rental', 'r-108', 'active', 'demo-seller', '06-10 09:00'],
  ['rental', 'r-108', 'completed', 'demo-seller', '06-13 11:00'],
  ['transportJob', 'tj-101', '募集中', 'demo-seller', '09-08 09:00'],
  ['transportJob', 'tj-101', 'approved', undefined, '09-08 09:30'],
  ['transportJob', 'tj-101', '調整中', 'demo-seller', '09-09 18:00'],
  ['transportJob', 'tj-101', '運搬中', 'okada', '09-13 08:05'],
  ['transportJob', 'tj-102', '募集中', 'ito-farm', '09-05 14:00'],
  ['transportJob', 'tj-102', 'approved', undefined, '09-05 14:20'],
  ['transportJob', 'tj-102', '調整中', 'ito-farm', '09-11 17:30'],
  ['transportJob', 'tj-103', '募集中', 'kato', '09-13 07:45'],
  ['transportJob', 'tj-104', '募集中', 'nakamura-farm', '06-28 10:00'],
  ['transportJob', 'tj-104', 'approved', undefined, '06-28 10:30'],
  ['transportJob', 'tj-104', '調整中', 'nakamura-farm', '06-30 09:00'],
  ['transportJob', 'tj-104', '運搬中', 'yamamoto-transport', '07-05 08:00'],
  ['transportJob', 'tj-104', '完了', 'nakamura-farm', '07-05 15:40'],
]

const dealEvents: DealEvent[] = eventSeeds
  .map(([dealKind, dealId, status, actorUserId, when, note], index) => ({
    id: `ev-${String(index + 101)}`,
    dealKind,
    dealId,
    status,
    actorUserId,
    note,
    createdAt: at(when),
  }))
  .sort((a, b) => b.createdAt.localeCompare(a.createdAt))

export const demoActivity: DemoActivity = {
  listings,
  transportJobs,
  submissions,
  messages,
  rentals,
  orders,
  reviews,
  carrierProfiles,
  notifications,
  threadReads,
  accountStatuses,
  dealEvents,
}
